[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[alias]
lint = "clippy -- -D warnings"
r    = "run"
rr   = "run --release"
b    = "build"
br   = "build --release"
